# Generated by Django 5.2.1 on 2025-06-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pillow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillow_code', models.CharField(max_length=14, unique=True)),
                ('aquisition_date', models.DateField()),
                ('category', models.CharField(choices=[('kids', 'Kids'), ('elders', 'Elders'), ('baby', 'Baby'), ('travels', 'Travels'), ('outlet', 'Outlet')], max_length=20)),
                ('quantity', models.CharField(max_length=4)),
                ('outlet', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=10)),
                ('promotion_value', models.CharField(blank=True, max_length=10, null=True)),
                ('dealer', models.CharField(max_length=20)),
            ],
        ),
    ]
