# Generated by Django 5.1.6 on 2025-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillow', '0002_pillow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillow',
            name='name',
            field=models.CharField(default='Travisseiro de pluma', max_length=51),
        ),
    ]
